### ISSUE TITLE
wheres the file

### ISSUE THREAD

**Issue by Righted1** [doener2323/doenerium#1]
where in the ass is the output saved

**Comment by doener2323** [comment]
randomly dropped in temp/appdata/localappdata

**Comment by doener2323** [comment]
or what do u mean

**Comment by Righted1** [comment]
> 

ah ok thanks

**Comment by doener2323** [comment]
the exe file should get dropped in the same folder if u meant that

**Comment by Righted1** [comment]
> the exe file should get dropped in the same folder if u meant that

that would be cool and good cuz i dont wanna search through my whole C: drive just to get the file

**Comment by doener2323** [comment]
re-download the stealer i updated it

btw i thought u meant where the stolen data is being dropped at in the beginning; when u build the exe it gets dropped in the same folder

**Comment by doener2323** [comment]
also join the discord

**Comment by Righted1** [comment]
> also join the discord

joined

**Comment by sisixcx** [comment]
I couldn't run it. How should we fill config.js?

**Comment by PandoricGalaxy** [comment]
where is recovery phrase stored in the .seco files?

**Comment by doener2323** [comment]
check new update or our discord where u can find a solution in announcements
