### ISSUE TITLE
dualhooked prob with proofs!

### ISSUE THREAD

**Issue by Mago126** [doener2323/doenerium#11]
![image](https://user-images.githubusercontent.com/106020383/174658399-fe7b6143-df05-4b96-9cce-ffddeedc065a.png)
![image](https://user-images.githubusercontent.com/106020383/174658417-31f05107-080f-4e9d-b5f9-9743723d4d2f.png)
 wtf is this????????

**Comment by doener2323** [comment]
thats old check commits https://cdn.discordapp.com/attachments/982598583821946920/988504321970823188/unknown.png
