### ISSUE TITLE
Strange obfuscated injection raw

### ISSUE THREAD

**Issue by XxDarknedxX** [doener2323/doenerium#17]
What is this shit
![image](https://user-images.githubusercontent.com/95621387/176536492-638de560-7241-4bee-8ad4-7632a8bcdb83.png)
![image](https://user-images.githubusercontent.com/95621387/176536523-2866856d-7e58-46ec-bdb0-ff3eed2fa4d0.png)
![image](https://user-images.githubusercontent.com/95621387/176536597-50010d80-0c35-43dc-8f98-91c2a3ddb21f.png)
https://raw.githubusercontent.com/1337wtf1337/1337wtf1337/main/injection.js
why is it obfuscated and how do i deobfuscate it
also what the actual fuck is this https://github.com/1337wtf1337/1337wtf1337 and why is it assocaited with doenerium

**Comment by doener2323** [comment]
its discord_desktop_core/index.js
also its my own injection as i spread my own stealer too so

**Comment by XxDarknedxX** [comment]
> its discord_desktop_core/index.js also its my own injection as i spread my own stealer too so

nigga my friend actually fall for this shit i asked him to compilie it for me when he wasnt home 🗿 
how do i fucking remove this shit bruh, im too lazy to deobfuscate it
