### ISSUE TITLE
Stub doesnt run

### ISSUE THREAD

**Issue by PandoricGalaxy** [doener2323/doenerium#2]
![image](https://user-images.githubusercontent.com/86944806/168066514-2931fd81-9d0c-4456-9cd3-197f430d2c8a.png)
I was running the index-win.exe on apponfly rdp trial to test it and it didnt run
What did i do wrong?

**Comment by doener2323** [comment]
hey, can u add me on discord: doener#2222

**Comment by PandoricGalaxy** [comment]
Final Update:

Spent time with doener2323 and its fixed now!
![image](https://user-images.githubusercontent.com/86944806/168096498-27936fe8-55f7-4b98-8e04-b8aae82de82d.png)
